version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Dhaka"
    target-branch: "main"
    labels:
      - "dependencies"
      - "npm"
    versioning-strategy: increase
    groups:
      minor-patch-deps:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    open-pull-requests-limit: 5
    reviewers:
      - "mrpie-db"
    assignees:
      - "mrpie-db"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    ignore:
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react-dom"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Dhaka"
    labels:
      - "dependencies"
      - "github-actions"
    reviewers:
      - "mrpie-db"
